project_id = "odmxffgnjloqzzaatffx"

[functions.gerar-pedido-pdf]
verify_jwt = false

[functions.notificar-lead-contato]
verify_jwt = false

[functions.buscar-clipping]
[functions.buscar-clipping]
verify_jwt = false

[functions.atualizar-senha-admin]
verify_jwt = false

