// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/listar-modelos.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
var MODELOS = [
  { slug: "aumark-s315", nome: "AUMARK S315", categoria: "diesel", capacidade: "3,5 t", cnh: "B" },
  { slug: "aumark-715", nome: "AUMARK 715", categoria: "diesel", capacidade: "7 t", cnh: "C" },
  { slug: "aumark-916", nome: "AUMARK 916", categoria: "diesel", capacidade: "9 t", cnh: "C" },
  { slug: "aumark-1217", nome: "AUMARK 1217", categoria: "diesel", capacidade: "12 t", cnh: "C" },
  { slug: "auman-d-1722", nome: "AUMAN D 1722", categoria: "diesel", capacidade: "17 t", cnh: "C" },
  { slug: "auman-d-1830", nome: "AUMAN D 1830", categoria: "diesel", capacidade: "18 t", cnh: "C" },
  { slug: "auman-d-2632", nome: "AUMAN D 2632", categoria: "diesel", capacidade: "26 t", cnh: "E" },
  { slug: "tunland-v9", nome: "TUNLAND V9", categoria: "picape", capacidade: "1 t", cnh: "B" },
  { slug: "tunland-v7", nome: "TUNLAND V7", categoria: "picape", capacidade: "1 t", cnh: "B" },
  { slug: "ewonder", nome: "eWONDER", categoria: "eletrico", capacidade: "1,2 t", cnh: "B" },
  { slug: "etoano", nome: "eTOANO", categoria: "eletrico", capacidade: "3,5 t", cnh: "B" },
  { slug: "eview", nome: "eVIEW", categoria: "eletrico", capacidade: "3,5 t", cnh: "B" },
  { slug: "ev-connect", nome: "eV CONNECT", categoria: "eletrico", capacidade: "1,5 t", cnh: "B" },
  { slug: "eaumark-9t", nome: "eAUMARK 9T", categoria: "eletrico", capacidade: "9 t", cnh: "C" },
  { slug: "eaumark-12t", nome: "eAUMARK 12T", categoria: "eletrico", capacidade: "12 t", cnh: "C" },
  { slug: "iblue-6t", nome: "iBLUE 6T", categoria: "eletrico", capacidade: "6 t", cnh: "C" }
];
var listar_modelos_default = defineTool({
  name: "listar_modelos",
  title: "Listar modelos Foton",
  description: "Lista os modelos de caminh\xF5es e picapes Foton dispon\xEDveis na Lavoro Foton, opcionalmente filtrados por categoria (diesel, eletrico, picape).",
  inputSchema: {
    categoria: z.enum(["diesel", "eletrico", "picape"]).optional().describe("Filtro opcional por categoria.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ categoria }) => {
    const itens = categoria ? MODELOS.filter((m) => m.categoria === categoria) : MODELOS;
    const linhas = itens.map((m) => `- ${m.nome} (${m.categoria}, ${m.capacidade}, CNH ${m.cnh}) \u2014 https://lavorofoton.com.br/modelos/${m.slug}`);
    return {
      content: [{ type: "text", text: `${itens.length} modelo(s):
${linhas.join("\n")}` }],
      structuredContent: { modelos: itens }
    };
  }
});

// src/lib/mcp/tools/contato-whatsapp.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
var WHATSAPP = "+5531996970656";
var contato_whatsapp_default = defineTool2({
  name: "gerar_link_whatsapp",
  title: "Gerar link de contato WhatsApp",
  description: "Gera um link direto de WhatsApp para o consultor Lavoro Foton, com mensagem pr\xE9-preenchida sobre o interesse do cliente.",
  inputSchema: {
    mensagem: z2.string().min(1).max(500).describe("Mensagem inicial que o cliente enviaria ao consultor."),
    modelo: z2.string().optional().describe("Nome ou slug do modelo de interesse, se houver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ mensagem, modelo }) => {
    const texto = modelo ? `${mensagem} (Modelo de interesse: ${modelo})` : mensagem;
    const url = `https://wa.me/${WHATSAPP.replace(/\D/g, "")}?text=${encodeURIComponent(texto)}`;
    return {
      content: [{ type: "text", text: `Link WhatsApp: ${url}` }],
      structuredContent: { url, telefone: WHATSAPP, mensagem: texto }
    };
  }
});

// src/lib/mcp/tools/info-empresa.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var info_empresa_default = defineTool3({
  name: "info_empresa",
  title: "Informa\xE7\xF5es da Lavoro Foton",
  description: "Retorna informa\xE7\xF5es institucionais da Lavoro Foton: concession\xE1ria oficial Foton em Minas Gerais, canais de contato e links \xFAteis (calculadora TCO, imprensa, modelos).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      nome: "Lavoro Foton",
      descricao: "Concession\xE1ria oficial Foton em Minas Gerais \u2014 caminh\xF5es diesel, el\xE9tricos e picapes Tunland.",
      whatsapp: "+55 31 99697-0656",
      site: "https://lavorofoton.com.br",
      links: {
        modelos: "https://lavorofoton.com.br/modelos",
        calculadora_tco: "https://lavorofoton.com.br/calculadora",
        comparativo_aumark: "https://lavorofoton.com.br/comparativo-aumark-1217",
        comparativo_ewonder: "https://lavorofoton.com.br/comparativo-ewonder",
        imprensa: "https://lavorofoton.com.br/imprensa",
        contato: "https://lavorofoton.com.br/contato"
      }
    };
    return {
      content: [{ type: "text", text: `Lavoro Foton \u2014 ${info.descricao}
WhatsApp: ${info.whatsapp}
Site: ${info.site}` }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "lavoro-foton-mcp",
  title: "Lavoro Foton MCP",
  version: "0.1.0",
  instructions: "Servidor MCP da Lavoro Foton (concession\xE1ria oficial Foton em MG). Use `listar_modelos` para consultar a linha de caminh\xF5es e picapes, `info_empresa` para dados institucionais e links \xFAteis, e `gerar_link_whatsapp` para produzir um link direto de contato com o consultor.",
  tools: [listar_modelos_default, info_empresa_default, contato_whatsapp_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
